spring.application.name=training_management_system_api





spring.datasource.url=jdbc:postgresql://localhost:5432/training_management_system_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create